//! Exercises the local library against real tagged audio files.
//!
//! The fixtures under `tests/fixtures/library` are generated by ffmpeg and
//! carry genuine FLAC/ID3/Vorbis tags, including one file with embedded cover
//! art and one with no tags at all, because the interesting behaviour is in how
//! the scanner handles the untidy cases.

use std::path::{Path, PathBuf};

use ymusic_lib::library::Library;

fn fixture_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/library")
}

/// Each test gets its own temp directory, so a stale art cache or database from
/// a previous run cannot make a test pass or fail spuriously.
struct TempHome(PathBuf);

impl TempHome {
    fn new(name: &str) -> Self {
        let dir = std::env::temp_dir().join(format!("ymusic-library-test-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("temp dir");
        Self(dir)
    }

    fn library(&self) -> Library {
        Library::open(&self.0.join("library.sqlite3"), self.0.join("art")).expect("open library")
    }
}

impl Drop for TempHome {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

#[test]
fn scans_a_folder_and_reads_tags() {
    let home = TempHome::new("scan");
    let library = home.library();

    library.add_folder(&fixture_dir()).expect("add folder");
    let report = library.scan_folder(&fixture_dir()).expect("scan");

    assert_eq!(report.failed, vec![], "no fixture should fail to parse");
    assert_eq!(report.added, 3, "two tagged files plus the untagged one");

    let tracks = library.tracks().expect("tracks");
    assert_eq!(tracks.len(), 3);

    let first = tracks.iter().find(|t| t.title == "First Light").expect("tagged flac");
    assert_eq!(first.artist, "Nebula");
    assert_eq!(first.album.as_deref(), Some("Drift"));
    assert_eq!(first.track_number, Some(1));
    assert_eq!(first.year, Some(2021));
    assert_eq!(first.codec, "flac");
    assert!(first.id.starts_with("local:"), "ids are namespaced: {}", first.id);
    let duration = first.duration_ms.expect("flac reports a duration");
    assert!((1900..=2100).contains(&duration), "expected ~2s, got {duration}ms");
}

#[test]
fn falls_back_to_the_filename_when_a_file_has_no_tags() {
    let home = TempHome::new("untagged");
    let library = home.library();
    library.add_folder(&fixture_dir()).expect("add folder");
    library.scan_folder(&fixture_dir()).expect("scan");

    let untagged = library
        .tracks()
        .expect("tracks")
        .into_iter()
        .find(|t| t.path.ends_with("untagged.ogg"))
        .expect("the untagged fixture is indexed rather than skipped");

    assert_eq!(untagged.title, "untagged");
    assert_eq!(untagged.artist, "Unknown Artist");
    assert_eq!(untagged.album, None);
}

#[test]
fn ignores_files_that_are_not_audio() {
    let home = TempHome::new("nonaudio");
    let library = home.library();
    library.add_folder(&fixture_dir()).expect("add folder");
    library.scan_folder(&fixture_dir()).expect("scan");

    let readme = library.tracks().expect("tracks").into_iter().find(|t| t.path.ends_with(".txt"));
    assert!(readme.is_none(), "readme.txt must not be indexed");
}

#[test]
fn extracts_embedded_cover_art_to_the_cache() {
    let home = TempHome::new("art");
    let library = home.library();
    library.add_folder(&fixture_dir()).expect("add folder");
    library.scan_folder(&fixture_dir()).expect("scan");

    let with_art = library
        .tracks()
        .expect("tracks")
        .into_iter()
        .find(|t| t.title == "Second Light")
        .expect("the mp3 fixture");

    let art = with_art.cover_art.expect("the mp3 carries an attached picture");
    assert!(Path::new(&art.path).exists(), "art is written to disk at {}", art.path);
    assert_eq!((art.width, art.height), (64, 48), "dimensions are read from the JPEG header");

    let without_art =
        library.tracks().expect("tracks").into_iter().find(|t| t.title == "First Light").unwrap();
    assert!(without_art.cover_art.is_none());
}

#[test]
fn a_rescan_skips_unchanged_files() {
    let home = TempHome::new("rescan");
    let library = home.library();
    library.add_folder(&fixture_dir()).expect("add folder");

    let first = library.scan_all().expect("first scan");
    assert_eq!(first.added, 3);
    assert_eq!(first.unchanged, 0);

    let second = library.scan_all().expect("second scan");
    assert_eq!(second.added, 0, "nothing changed on disk");
    assert_eq!(second.unchanged, 3, "every file is skipped by mtime");
}

#[test]
fn search_matches_title_artist_and_album() {
    let home = TempHome::new("search");
    let library = home.library();
    library.add_folder(&fixture_dir()).expect("add folder");
    library.scan_all().expect("scan");

    assert_eq!(library.search("first").expect("by title").len(), 1);
    assert_eq!(library.search("nebula").expect("by artist").len(), 2);
    assert_eq!(library.search("drift").expect("by album").len(), 2);
    assert_eq!(library.search("  ").expect("blank is everything").len(), 3);
    assert_eq!(library.search("nothing here").expect("no match").len(), 0);
}

#[test]
fn resolve_produces_a_lease_that_never_expires() {
    let home = TempHome::new("resolve");
    let library = home.library();
    library.add_folder(&fixture_dir()).expect("add folder");
    library.scan_all().expect("scan");

    let track = library.tracks().expect("tracks").into_iter().next().expect("at least one track");
    let lease = library.resolve(&track.id).expect("resolve");

    assert_eq!(lease.track_id, track.id);
    assert!(lease.url.starts_with("file://"), "got {}", lease.url);
    assert_eq!(lease.expires_at, None, "a file on disk does not expire");
    assert!(lease.headers.is_empty());
    assert!(!lease.is_premium_format);
    assert_eq!(lease.itag, None);
}

#[test]
fn resolving_a_moved_file_reports_the_path_rather_than_failing_in_mpv() {
    let home = TempHome::new("moved");
    let library = home.library();

    // A folder we own, so we can delete out from under the index.
    let scratch = home.0.join("scratch");
    std::fs::create_dir_all(&scratch).unwrap();
    let copied = scratch.join("01.flac");
    std::fs::copy(fixture_dir().join("Nebula/01.flac"), &copied).unwrap();

    library.add_folder(&scratch).expect("add folder");
    library.scan_all().expect("scan");
    let track = library.tracks().expect("tracks").into_iter().next().expect("one track");

    std::fs::remove_file(&copied).unwrap();

    let err = library.resolve(&track.id).expect_err("a missing file is an error");
    assert!(err.to_string().contains("no longer on disk"), "got: {err}");
}

#[test]
fn removing_a_folder_forgets_its_tracks() {
    let home = TempHome::new("remove");
    let library = home.library();
    let folder = fixture_dir().canonicalize().unwrap();

    library.add_folder(&folder).expect("add folder");
    library.scan_all().expect("scan");
    assert_eq!(library.tracks().expect("tracks").len(), 3);

    library.remove_folder(&folder.to_string_lossy()).expect("remove");
    assert_eq!(library.folders().expect("folders"), Vec::<String>::new());
    assert_eq!(library.tracks().expect("tracks").len(), 0, "tracks go with the folder");
}

#[test]
fn a_deleted_file_is_pruned_on_the_next_scan() {
    let home = TempHome::new("prune");
    let library = home.library();

    let scratch = home.0.join("scratch");
    std::fs::create_dir_all(&scratch).unwrap();
    std::fs::copy(fixture_dir().join("Nebula/01.flac"), scratch.join("a.flac")).unwrap();
    std::fs::copy(fixture_dir().join("Nebula/02.mp3"), scratch.join("b.mp3")).unwrap();

    library.add_folder(&scratch).expect("add folder");
    assert_eq!(library.scan_all().expect("scan").added, 2);

    std::fs::remove_file(scratch.join("b.mp3")).unwrap();
    let report = library.scan_all().expect("rescan");

    assert_eq!(report.removed, 1);
    assert_eq!(library.tracks().expect("tracks").len(), 1);
}
